sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)    
before_install:
    - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
    - sudo dpkg -i packages-microsoft-prod.deb
    - sudo apt-get update
    - sudo apt-get install -y apt-transport-https
    - sudo apt-get install -y dotnet-sdk-3.1
script:
    - dotnet restore
    - dotnet build --configuration Release
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t padmakumarnkg/inventorymanagement .
    - docker push padmakumarnkg/inventorymanagement:latest
    - docker push padmakumarnkg/inventorymanagement:$SHA